name: c#-dotnet

on:
  # run it on push to the default repository branch
  # Only if there are changes on the 'c#-dotnet' directory
  push:
    paths:
    - c#-dotnet/**
    - .github/workflows/ci-c#-dotnet.yaml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      - name: Install dependencies
        working-directory: ./c#-dotnet
        run: dotnet restore "listingapi.csproj"
      - name: Test
        working-directory: ./c#-dotnet
        run: dotnet test "tests/listingapi.unittests/listingapi.unittests.csproj" --logger "trx;LogFileName=test-results.trx"
      - name: Test Report
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
            name: listingapi Tests
            path: "test-results.trx"
            reporter: dotnet-trx
            fail-on-error: true
