name: "Lint OpenAPI specifications"

on: [push]

jobs:
  lint_openapi:
    runs-on: ubuntu-latest
    container: stoplight/spectral:6.6.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        working-directory: ./schemas
        run: spectral lint *.yaml --fail-severity hint
