name: TypeScript React

on:
  push:
    paths:
    - typescript-react/**
    - .github/workflows/ci-typescript-react.yaml

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        working-directory: ./typescript-react
        run: docker build -t typescript-react .

      - name: Test
        working-directory: ./typescript-serverless
        run: docker run -it typescript-react npm run test

      - name: Lint
        working-directory: ./typescript-serverless
        run: docker run -it typescript-react npm run lint
